image:
  repository: dkrinitsyn/youtube-to-text-unit
  pullPolicy: Always
  tag: "0"

replicaCount: 1

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

env:
  RABBITMQ_URL: "amqp://guest:guest@rabbitmq.rabbitmq.svc.cluster.local/"
  CHUNK_SIZE_CHARS: "4500"
  CHUNK_OVERLAP_CHARS: "400"
  DB_SCHEMA: "youtube_to_text_unit"

namespace: youtube-to-text-unit
